### PR TITLE
Fix lyrics lag active session, disable BroadcastReceiver API 19+

### PR DESCRIPTION
**Pull request by svenoaks**

### CODE REVIEW

**Comment by geecko86** [comment]
Interesting. I'll check it out later today. 
Can I ask which version of Android you've tested this on?

**Comment by svenoaks** [comment]
Nexus 9 - 7.1.1
Moto X Pure - 6.0

I can repo on both and it fixes, though there are some other issues on the Nexus 9, not caused by commit, with showing lyrics a track behind, and not showing cover art image. I'll see if i can figure out more.

**Comment by geecko86** [comment]
Right, I think it's because you looked at the Broadcast Receiver (required for ICS & JB support), while the real deal is the NotificationListener these days.

One other bug that's really been driving me insane is that Spotify will often send the previous Artwork instead of the current one. I'm pretty sure that's an actual bug in their app (I can see the same thing happening on my watch), but I'd love to work around that.

Lots of other things on my plate at the moment, though.

**Comment by svenoaks** [comment]
Oh the BroadcastReceiver is still active on >= 5.0 though? Could it just be to disable it?

**Comment by svenoaks** [comment]
It can work with BroadcastReceiver disabled on those devices, and it doesn't have the bug. Why not put values-v18.xml with bool for disable the BroadcastReceiver?

**Comment by geecko86** [comment]
Note: RemoteController.OnClientUpdateListener appeared in KitKat and 
the OnActiveSessionsChangedListener appeared in Lollipop, so it should be v19.

Actually, the NotificationListener currently sends a broadcast to the BroadcastReceiver. It's a bit dirty but it's only temporary:

Since Android O will make registering BroadcastReceivers in the manifest illegal, I was planning to wait for a while and then completely remove support for API < 19, and getting rid of the BroadCastReceiver along with it.

You're right, disabling the BroadcastReceiver for devices running 19+ already makes sense now. It's always tricky because you never know if it's gonna break support for some obscure player, which is why I left it.

**Comment by geecko86** [comment]
Hmm.. it's hard to say for sure because it's not very consistent - but I just tried disabling the NotificationListener and relying exclusively on the BroadcastListener (my phone runs 7.1.1).

The Spotify bug I mentioned earlier seems to be gone. Again, it's hard to say for sure. (And you need to enable a specific settings in Spotify for it to send broadcasts)

**Comment by geecko86** [comment]
Deleted this comment without meaning to:

> RemoteController.OnClientUpdateListener was introduced in KitKat, so it should be v19+.

> I was going to wait for the Android O release, since it makes registering receivers in the manifest illegal. I thought this would be the right time to cut support for devices running ICS and JB.

> You're right, removing the broadcast receivers now makes sense - it's just tricky because it could maybe break support for some obscure player. I think it's worth trying though.

The Spotify bug I mentioned was not solved by disabling either the BroadcastReceiver or the NotificationListener - it happens with both.

Feel free to update your PR with the changes you suggested. 👍

**Comment by svenoaks** [comment]
I believe the issue with Spotify art is because you did not override onMetaDataChanged MediaController callback. What it probably does is set the artist, title, etc, setMetaData(), start the image loading asychronously, then setPlaybackState(). Later it receives image and only setMetaData () again. Image load is sychronous if its in cache which is why not consistent.

Some players will set the artist, title only after they receive image possibly async, which is why you can the track behind problem. It totally fixed it on my Nexus, its always on right track now. Let me know if it fixes Spotify problem for you.

Is there reason for `controllers.get(0)` every time or can we use `controller` from `onActiveSessionsChanged`? Also may not need previous change to BroadcastReceiver anymore and need to verify on API 19 and below.

**Comment by svenoaks** [comment]
Also I had question, why not use MediaControllerCompat for all API's?

**Comment by svenoaks** [comment]
Oh I see why not MediaControllerCompat, no compat MediaSessionManager.

**Comment by geecko86** [comment]
> Is there reason for controllers.get(0) every time or can we use controller from onActiveSessionsChanged?

Not sure I understand?
**onActiveSessionsChanged** only has 1 argument, which is a List of controllers. There is no **controller** argument. 

> I believe the issue with Spotify art is because you did not override onMetaDataChanged 

I'm surprised I never tried this. I'll try out your changes now. Thanks!

**Comment by svenoaks** [comment]
I just mean like the above, I don't think there is a reason to get(0) everytime unless you think it could get reassigned in between callbacks.

**Comment by geecko86** [comment]
Right, sorry. No point in calling controllers.get(0) every time - you did well to remove that.

#191 is still occurring - I'll look into it now. What you said about the asynchronous loading makes sense.

**Comment by svenoaks** [comment]
Oh, I can see it now, pause it then change the song.

**Comment by geecko86** [comment]
Yup.

Also I just remembered why the VLC package name is blacklisted. They're sending the wrong information over that channel - "fd://0" at the title or something of the sort.

The info they broadcast is the right one, though (I'm the one who sent them the Pull Request for that), so I was relying on the broadcast receiver for all API versions, not just 19+. This means I can't merge your Pull Request until they correct their implementation.

**Comment by svenoaks** [comment]
VLC seems to be fine when not blacklisted, and increasing the paused ignore time seems to make Spotify art problem not happen and switching between players work better (sometimes it was ie 218 ms on my device)

**Comment by svenoaks** [comment]
Hmm Spotify art still happens sometimes tho

**Comment by geecko86** [comment]
Playing a video in VLC results in me getting metadata like "Unknown Artist" and "filename.mp4". Same thing if I push an MP3 to my device with ADB and read it with VLC without rebooting it first.

How about blacklisting Spotify in onPlaybackStateChanged but not in onMetadataChanged?
That seems to work for me.

**Comment by geecko86** [comment]
I'm not sure about your idea of sleeping for 500ms, to be honest. Seems a bit dirty.

**Comment by geecko86** [comment]
I should probably test things out on a KitKat device, I'll see if I can find the time to flash my old Nexus 4.

**Comment by svenoaks** [comment]
It's dirty but there are multiple broadcasts nearly simultaneously when track changes and not in the right order. I think a little better (at least for 21+) is to post delayed for something like 3 seconds, and ignore all playback and metadata changed in that time, then read the current states and send the broadcast. That way you get only one broadcast and it will be after all the asynchronous stuff happens in the player.

**Comment by geecko86** [comment]
3 seconds is way too long to wait. The app is meant to react as quickly as possible. It will also break the synchronized lyrics, though we can probably fix that.

Also, sometimes the first update you get is for the previous track, ignoring a bunch of them is dangerous. For instance, when changing from track A to track B, some players will do this:

* Track: "A", isPlaying: true
* Track: "A", isPlaying: false
* Track: "B", isPlaying: true

**Comment by svenoaks** [comment]
Yeah i forgot about sync'd lyrics. The other thing can be overcome because you can always read the current state, if the controller is the right one, ie MediaMetadata metadata = controller.getMetadata();, but it doesn't matter because of syncing lyrics.

I don't think the ignoring paused broadcasts for 500ms is that bad, I don't think it will go wrong, unless they are spamming buttons or something.

**Comment by geecko86** [comment]
Right now my device has your changes for disabling the receiver, removing VLC from the black list and adding onMetadataChanged(), as well as my change which blacklists Spotify in onPlaybackStateChanged().

(I was only able to reproduce #191 once with these changes)

> there are multiple broadcasts nearly simultaneously when track changes and not in the right order.

Can you describe a scenario I can reproduce right now which causes the app to misbehave like that? Right now I haven't seen anything like that and so I can only see a downside to what you're suggesting.

**Comment by svenoaks** [comment]
Press play Google Play Music, press forward track on Spotify, QuickLyric won't update to the Spotify song unless you have the 500ms thing it seems.

**Comment by svenoaks** [comment]
Another thing I thought of is you are unregisterCallback on controllers[0]. I don't think that is the one you registered it on previously since now a different one is [0]. Maybe it would cut down on the spam because  you still have old ones with callbacks.

**Comment by geecko86** [comment]
> Press play Google Play Music, press forward track on Spotify, QuickLyric won't update to the Spotify song unless you have the 500ms thing it seems.

[Like this?](https://dl2.pushbulletusercontent.com/CyhLjyVmGLsH1Cc5C4Y30iav8UBswLME/ScreenRecord-2017-04-01-18-40-34.mp4) If so, I was not able to reproduce it.

> I don't think that is the one you registered it on previously since now a different one is [0]

I guess we could do a for loop and call unregisterCallback on all of them?

**Comment by svenoaks** [comment]
Maybe because you squelch playbackstate of Spotify which I didn't have. Might as well take out the 500ms in that case, Spotify was the only one I could still make it happen with the other changes. 

Yeah you could unregister them in loop but I don't think it matters, I looked at it on debug and it appears system unregisters them automatically for inactive sessions already when it is called.

**Comment by geecko86** [comment]
Awesome, can you squash all this in a 1 or 2 commits? If you could also add a line to ignore spotify in onPlaybackStateChanged (`if (packageName.contains("spotify"))`or so), that would be awesome. I'll merge it right away.

**Comment by svenoaks** [comment]
Also fixed  - start Spotify playing. Install app. - press skip track on spotify. Does not pick it up because active session has not changed.

**Comment by geecko86** [comment]
I'll check it out. I'm not sure I understand your last comment though.

Can you reduce your 10 commits to one or two? I'm not super into commits that are named "ugh" :smile:

**Comment by svenoaks** [comment]
I'm not sure how to do it on my end without making new pull request - I believe there is option to do Squash and Merge if you have write permission on the github repo.

The last thing was - it only registers the playbackstate and metadata callbacks when the active sessions change. If the service starts when MediaSession is active, it won't won't pick up the metadata changing, so I register it on onCreate(). I think you wouldn't have this problem before the BroadcastReceiver is disabled for 19+ because the BroadcastReceiver would pick up the slack.

I still have the problems sometimes when switching players, without the 500ms thing. What about making the FAB refresh button set it from the current active session controller data instead of what was last set, how doable is that for at least API 21+?

**Comment by geecko86** [comment]
You can squash your commits with [git rebase](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) and then use `git push --force`` to replace what you pushed so far.

> If the service starts when MediaSession is active, it won't won't pick up the metadata changing, so I register it on onCreate().

Sure, that makes sense. Nice find.

> I still have the problems sometimes when switching players, without the 500ms thing. What about making the FAB refresh button set it from the current active session controller data instead of what was last set, how doable is that for at least API 21+?

We can try it. Push it and we'll both do some testing for a while, especially regarding the impact it has on synchronized lyrics (pausing and resuming really fast, etc.)

Again, thank you for this!

**Comment by svenoaks** [comment]
these changes seem to have already broken the sync'd lyrics on my device, any idea where to start looking?

**Comment by geecko86** [comment]
I'm not seeing your 500ms trick in this commit. Changed your mind?

When you say it's broken, do you mean the timing's off? I don't see anything broken here, but I'm testing on the branch that connects to the QuickLyric API.

The quality of the synchronized lyrics you'll get from ViewLyrics (the provider used on the GitHub branch) is very variable. When debugging the synchronized lyrics, try putting a breakpoint somewhere in the LRCView and grab the LRC String inside the Lyrics object. Paste it in a notepad and switch back to Spotify. If you notice that the timecode you got from ViewLyrics was wrong to begin with, there's nothing you can do about it and the build that's on the Play Store will not have this issue. Also make sure you're not using a bluetooth headset or something that causes a delay. 

Also, if you're playing from a streaming service, you might need to hit "Resync" in the action bar. I think this is happening more often than before, actually. Not sure.

Also, I just had #191 again.

**Comment by svenoaks** [comment]
I mean I don't see highlighted lyrics at all, when the same song from the play store has the sync'd lyrics. What songs can I use that work on github version?

**Comment by geecko86** [comment]
"Money" by Pink Floyd

**Comment by svenoaks** [comment]
When I do Money it comes from lyrics.wikia.com and mLRC is false.

**Comment by geecko86** [comment]
You need to enable it in the settings, it's disabled by default.

**Comment by svenoaks** [comment]
This has the same effect as the 500ms thing, but more clean. The inactive session callbacks are filtered. Even when onActiveSessionsChanged called and old is unregistered, the old one would call back because they're in message queue. Now it is changing between players correctly in all cases for me.

Can you see if [#191](https://github.com/geecko86/QuickLyric/issues/191) still happens like this, I can't make it happen.

**Comment by svenoaks** [comment]
ahh nvm I still get 191, looking more.

**Comment by geecko86** [comment]
As you can see, I tried to work around it by preventing saveArtwork() from saving a PNG if the bitmap for the last PNG that was saved has the same byte length as the current bitmap (private long previousArtworkSize). Kind of a desperate hack, but I'm surprised it hasn't paid off.

I keep being convinced that their implementation for that stuff needs to be reworked and that the only way we can solve this is by doing workarounds like this one.

Now that I think of it, blacklisting Spotify onPlayStateChanged was a terrible idea - it must have broken sync since it made it impossible to detect when the user had paused the song.

**Comment by svenoaks** [comment]
I see what's happening. One sec

**Comment by svenoaks** [comment]
Nailed #191  it I think. Here is what happens when the bug manifests:

callback #1                 New artist, title - old artwork
callback #2                New artist, title - new artwork
callback #3-many     New artist, title - new artwork

Size of Bitmap is always the same from Spotify, need to check `sameAs()`, and be willing to overwrite the file since the first one is the wrong artwork.

**Comment by svenoaks** [comment]
Though pretty pointless to write a file I guess, if it's just going to overwrite it everytime.

**Comment by geecko86** [comment]
Yeah you want to make sure it doesn't do pointless writes.

**Comment by svenoaks** [comment]
It can be - 
1) read file if it already exists and compare with the new one, only write if different. 
2) just skip the first artwork that comes in from Spotify on a new track (dirty, I guess)
3) Just put the Bitmap in a static somewhere and read it from memory instead of writing at all.

What is the point of saving it, I prefer 3), it is already in memory at this point.

**Comment by svenoaks** [comment]
or 4) It just rewrites if you change the track, then user plays the same track at a later time - this is the way it is, I think it's not so bad actually, if you want to display the artwork sometime when the music is not playing (saved lyrics?).

**Comment by geecko86** [comment]
The problem with 3) is that bitmaps are heavy and we already have #192. Right now the app uses over 100MB in memory, which is nuts. Storing the artwork in the cache directory is cleaner and a move in the right direction.

The problem with 1) is that you need to compress the bitmap every time, which, if it happens 4 times in a second, will noticeably drain performance. We need to be smarter.

I'm not sure I understand  4). How does it prevent us from writing Spotify's wrong artwork?

**Comment by svenoaks** [comment]
The bitmap is already in memory in the media session. 100 mb is not a lot, all my running apps use that much. 

In 1) you will not need to write or read it multiple times a second. You will only need to read it when the user comes back to the track after leaving it. But at that time you will write the wrong one from Spotify and the right one again, so on second thought it is a bad idea.

4) is what it is doing. It holds a reference to the last Bitmap (the same one in the media session), whenever it comes and it is different from the one it holds it writes it to file. So when the Spotify thing happens, it writes the wrong one, then writes the right one once. If the user were to change the track, and then come back to it, it will repeat the process.

I think if you want to save the lyrics to file (presumably you are displaying them from 'Saved lyrics'?) 4) may be the best you can do unless you want to ignore the first artwork that comes from Spotify (who knows, maybe other players do the same thing) which I guess is dirty.

**Comment by geecko86** [comment]
4) is essentially the current implementation except it doesn't hold a reference to the byteSize, but to the actual bitmap instead. I see.

When the spotify thing happens (say with the song "Money" by Pink Floyd) this is what will happen:

1. * If Money_PinkFloyd.png doesn't exist, write to that file and update the reference we hold
    * If it already exists, compare the two Bitmaps (the one we hold and the one we're getting). Only write to the file & update the reference if there's a difference.
2. Get a second update with the correct Bitmap and the same metadata
3. Write, since there's a difference
4. Get a bunch of other redundant updates after that
5. Skip, since there's no difference

Ok that makes sense. Sorry I just needed to get a clearer picture. Ideally I would prefer if we could do that with something lighter than a bitmap, but since you say they're always sending the same size, it won't work.

dc302e2 does 4), correct?

**Comment by svenoaks** [comment]
Yes you are right and 4) is what is in dc302e2. But there is a difference, you were also checking the file size and not writing if file size != 0, so it still wouldn't work even if the bitmap byte sizes were different.

You could hash the bitmaps, but that would be more cpu, and holding the Bitmap is not anything since it's already in the media session, its just a reference to the same memory, and they are going to go out of scope around the same time.

**Comment by svenoaks** [comment]
Nevermind you did `artworkFile.length() == 0 || (artwork.getByteCount() != this.previousArtworkSize`, it would have been effectively the same thing I believe, still writing the wrong one, then the right one, and rewriting when you go back to the track. 

But `getByteCount()` is always the same, so is `getAllocationByteCount()`

**Comment by geecko86** [comment]
Awesome, I just tried it and it works beautifully. Are we ready to merge?

**Comment by svenoaks** [comment]
How does it work on Android 4.4?

**Comment by geecko86** [comment]
It calls `saveArtwork()` from the KitKat-specific `onClientMetadataUpdate()`, so your changes should apply there too. But you're right, I should dust off my Nexus 4 and test it.

**Comment by geecko86** [comment]
Hum, seems like `Bitmap artwork = metadataEditor.getBitmap(MediaMetadataEditor.BITMAP_KEY_ARTWORK, null);` is Null on KitKat. The artist and title fields are good, though.

**Comment by geecko86** [comment]
Well, RemoteController seems to consistently never provide the Artwork bitmap, I tested three players including one that's open source and definitely puts the artwork in the metadata for the session. Same thing on Nougat, while it works with a MediaController.

One way to work around this might be to launch an Asynctask to search the MediaStore for an MP3 file that matches the metadata we've received and extract the bitmap from there.

**Comment by svenoaks** [comment]
I see why no artwork, one sec.

**Comment by geecko86** [comment]
Awesome, I'll try it out now. What does 510edd0 do exactly? Looks like it's just changing the default duration used when the info is not provided.

**Comment by svenoaks** [comment]
Yeah if it does not provide duration, I thought you meant to allow it to operate. At 60000 it is > 1200 and returns in the BroadcastReceiver without updating. It already allows tracks with no duration on Android 5.0+

I just noticed it because it didn't work 4.4 with my app because I don't put in duration or position.

**Comment by geecko86** [comment]
I can confirm it works like a charm on KitKat, thank you so much for this. 👍👌

> At 60000 it is > 1200 

I'm guessing the confusion here is really whether the time unit used here is milliseconds or seconds. For Spotify it seems to be milliseconds.

**Comment by geecko86** [comment]
Oh I see, the default I put in was an Integer, making it count as seconds. Ok good, great find.

**Comment by geecko86** [comment]
Many Chinese devices like Huawei, Xiaomi, Oppo, ... seem to think killing all services is a good idea to save battery and that users need to whitelist the services they want to allow.

We currently start an intent to ask the user to whitelist QuickLyric but that doesn't always translate well.

We should probably re-enable the BroadcastReceiver when we detect that the NotificationListener isn't running.

**Pull request merged**
