### PR TITLE
get all songs from spotify 

### LINKED ISSUE #170: Save all spotify tracks instead of just saved tracks
Hi,

A little back story : I use QL to download spotify lyrics from my library and for some reason it was only saving 8 songs always. 
So today I took a look at the code and saw that only the saved tracks are used to fetch lyrics. Not sure how other people use Spotify, but I never save a song. I store playlists for offline use. I imagine everyone doing the same. Downloading the playlist and when you add a song to it, the song gets automatically downloaded. 

So, I am wondering can we download lyrics for all the songs in the users library? It will be a huge number (I know people who have 1000's of songs). Is this feasible to do(api restrictions, too late in the project's timeline etc). If yes, let me know I can do this and submit a PR. Did a dirty version of this, and seems to work. Wanted to ask if this is something you would be interested in or not, before I look more into it. 

Thanks.

### PR DESCRIPTION
**Pull request by prashantkhurana**
Fixes #170

### CODE REVIEW

**Comment by geecko86** [comment]
Thanks. I've not had the time to test it yet, but is there a particular reason why you replaced the Retrofit Callback with an AsyncTask?

**Comment by prashantkhurana** [comment]
Thanks. Callback works in the UI thread, so I was getting NetworkOnMainThreadException for doing network calls on UI thread. There are ways to make Callback work on background thread but  AsyncTask is simpler, I think. The reason there were no exceptions before, was because there was only 1 network call (get saved tracks), now there are many.

**Comment by geecko86** [comment]
It's late here, so I'll check it out tomorrow.. But this part:

> The reason there were no exceptions before, was because there was only 1 network call (get saved tracks), now there are many.

is really disturbing to me. The type or the intensity of networking is, AFAIK, irrelevant and a NetworkOnMainThreadException will be thrown no matter what. I also don't think Retrofit uses the main thread in this case.

I'll investigate it tomorrow, but in the meantime if you manage to make it work with a Retrofit.Callback, It would be very appreciated.

No matter the case, I really appreciate the work you've put in this.

**Comment by prashantkhurana** [comment]
Yes, you're right. Using callbacks it won't run on the main thread. My bad. I was using non callback versions of the api. I'll convert it to use callbacks.

**Comment by prashantkhurana** [comment]
Did it. Was a fun experience. 
Personally, I prefer the AsyncTask method better than callbacks. Here's why : 
1) Callbacks execute on the main thread by default. So can't add non callback network calls in onSuccess method of a callback. That results in NetworkOnMainThreadException.
2) Callbacks are asynchronous. 

As callbacks are asynchronous, the way I had to write the code results in more network calls. The flow I wanted was a synchronous one where you get the user, then get the playlists and then for each playlist get all tracks. Achieving the same thing asynchronously is harder to understand and write. 

Also, I believe there is no advantage that callbacks give us. Because we are waiting with the progress dialog anyway so that we can ask the user if he wants to proceed with the download or not. I can see why the progress dialog is necessary. It keeps the user in loop. So then why asynchronous callbacks  should be used? It's not like we are continuing with other stuff in the meantime. 

Fun fact. I mentioned that we would be doing more network calls this way. The reason being I am fetching one playlist per time. I could not think of a way to get all playlists and then operate on them, due to asynchronous nature of callbacks. This is the only way I can think of which requires 0 asyncTask , 0 threads etc and uses just callbacks. 

Let me know how you feel about it. Either way you decide to approach, this was a fun experience, I must say.

**Comment by geecko86** [comment]
I'm glad you enjoyed it. I still think using callbacks in the only right approach.

I reviewed your code and it looks much better now. Your approach, using several inner-classes, is a bit different from how I usually work but in this case I think it makes sense.

One thing that disturbs me though, is this:

`private final int playListsToFetch = 1;`

You set the limit parameter to 1. Unless I'm mistaken, this means it will only download the tracks for the first playlist. Doesn't that defeat the purpose of issue #170?

If you do commit again, please try to squash your 5 commits into 1.

Thanks again!

**Comment by prashantkhurana** [comment]
Thanks. I'll squash everything. 

> Your approach, using several inner-classes, is a bit different from how I usually work but in this case I think it makes sense.

I used it this way because I need access to the parent object in one of the child and using using the 'new Callback' style didn't allow me to do that or I don't know how to do it. Plus this ends up with 3 levels of nesting which using 'new callback' made it really difficult to read. 

> private final int playListsToFetch = 1;

So I fetch a playlist, then get it songs, then fetch another and so on.

> if (playlistPager.next != null) {
                        SpotifyApi.getInstance().getApiService()
                                .getPlaylists(user.id, playlistPager.offset + playlistPager.limit, playListsToFetch, playListCallback);
}

This takes care of all the playlists. This is a weird way of making sure that we only proceed when we have every playlist's songs. Basically trying to sync in some way but using Callbacks. 

 It is done this way because I can't figure out a way to get all playlists and then iterate over them because of the async nature. So for each playlist I am making 2 calls, get playlist, then get all songs. More more bonus point o asyncTask here. I could get all playlists and then go over each one of them. 

Overall, I still feel Callbacks have made the code harder to read and more importantly, harder to reason why things are done the way are. The questions you asked , why inner classes are done that way and why playListsToFetch =1 are valid questions, but wouldn't have been raised in the asyncTask method of doing things.

**Pull request merged**
