### PR TITLE
starting Recent Tracks

### PR DESCRIPTION
**Pull request by svenoaks**
Take a look. One thing I need help on - there is no already in place way to load a lyrics that is not downloaded already, or that is the current track from the notification (what I'm currently mimicing now which isn't working very well). It's pretty Bzantine, can you help see if there is an easy way to update the LyricsViewFragment when clicking on the tracks from recents. I think maybe it will need to display a loading progress thing in the RecentTracksFragment when it's downloading, then switch fragments.

Also suggestions for things like 

1) Clear the whole list action? (Clearing one at a time seems unnecessary)
2) Add time stamp to each list item on the right (2 hours ago, etc)?
3) Headers which display things like 'Today', 'Yesterday', '2 days ago', etc. to group them.

### CODE REVIEW

**Comment by svenoaks** [comment]
And maybe I should persist it in a file instead of abusing SharedPreferences with Gson because it does auto-backup on them, which makes it weird, and the images won't be there because they are in file.

**Comment by svenoaks** [comment]
Now it will either retrieve lyrics from db or download when switching from Recent Tracks fragment but for some reason [693](https://github.com/geecko86/QuickLyric/pull/207/commits/20705ab90562aebe95c0afb747c1d2e48cd278e2#diff-6ed509e66c9372cdccd68ad12500e209R693) not actually showing the refresh thing.

**Comment by geecko86** [comment]
I've been pretty busy, but I'll check out your commits as soon as I can.

> One thing I need help on - there is no already in place way to load a lyrics that is not downloaded already

You can actually, that's how third party apps can plug into QuickLyric.
You can check out [this page](https://github.com/geecko86/QuickLyric/wiki/Integrating-QuickLyric-in-your-app), which in fact uses `lyricsFragment.fetchLyrics(artist, track);

You can also just use MainActivity's updateLyricsFragment() with those two arguments.

This stuff is very poorly documented, I'm sorry.

> Clear the whole list action?

What's a scenario where I would want to clear the recent tracks? It takes so little storage I'm thinking it's unnecessary. For instance I don't see that feature in Spotify.

> Add time stamp to each list item on the right?
> Headers which display things like 'Today', 'Yesterday', '2 days ago', etc. to group them.

Is this an information the user wants? Does it help him in any way?

I'm not saying we can't do it, but right now I really think we don't need to add complications where we don't need them. I think the "recently played" list in Spotify nails it perfectly. Simple yet efficient. Again, I'm absolutely open to debate this.

> And maybe I should persist it in a file instead of abusing SharedPreferences with Gson because it does auto-backup on them

If that's the only issue, it's easy to separate it from the rest of the app and [exclude it from the backup](https://developer.android.com/guide/topics/data/autobackup.html#XMLSyntax). I just opened #208.

**Comment by geecko86** [comment]
Still haven't tried it out (will do it later today) but regarding the preferences thing, right now you're using 

`PreferenceManager.getDefaultSharedPreferences(context);`

This will store the recent tracks inside the main preference file, which is `com.geecko.QuickLyric_preferences.xml`. In order to avoid the auto-backup issue, you should instead do:

`context.getSharedPreferences("recent_tracks", Context.MODE_PRIVATE);`

Which will store whatever you put in it inside `recent_tracks.xml`. I've already excluded that file from auto-backup (see #208).

**Comment by svenoaks** [comment]
I tried the intent that the notification uses which calls the updatelyricsfragment with the artist and title, but it didn't work very well, it only switched to the new lyrics part of the time. In fact there is a note which says it should only be called from Search and notification

**Comment by svenoaks** [comment]
But I have way to do it in SingleLyricsRetrievalSerivce

**Comment by geecko86** [comment]
Hey Steve. Thanks again for your contribution. I just merged it after some adjustements.

I will say you took a lot of liberties to move stuff around. I think you were right (most of the time, i.e. separating the providers and the models) but I do think it'd be better to discuss these things with the owner when you make changes of this magnitude :)

The stuff you did with the service wasn't necessary. It's really two fragments communicating with one another.

I redid the layout a bit. The stuff they say about not using cards in lists is exclusively because of the padding around the cards. In this case, there is no padding, the only goal is to have the rows elevated.

**Comment by geecko86** [comment]
Let me know if I forgot something. It seems to be working pretty well.

**Comment by svenoaks** [comment]
I think the `new DownloadThread` in `LyricsViewFragment` can cause out of order callbacks, I think it it should all be moved to an IntentService or some other kind of queue, which is why I was starting to use the service.

**Comment by geecko86** [comment]
Interesting. In what scenario can two `DownloadThread`s be triggered?

**Comment by svenoaks** [comment]
If you refresh the song and it has to download it, then go to the next song and it has to download it, or click on a recent track it has to download, there is no guarantee the callbacks will be as expected.  I think DownloadThread can also leak LyricsViewFragment through callback if it gets held up for awhile, I guess for a few minutes if it uses all the timeouts.

**Comment by svenoaks** [comment]
One easy way to demonstrate is turn on 'Automatically Refresh Lyrics' place 

`private static long delay = 25000;`

in DownloadThread

and 

```
delay -= 5000;
                if (delay < 0) delay = 0;
                try {
                    Thread.sleep(delay);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
```

in beginning of run().

Start program and skip tracks repeatedly from the notification drawer. You will get it turning the LyricsViewFragment to the earlier ones after the later. This kind of thing not unlikely with spotty network access and more likely to happen with recent tracks addition.

There should be a single queue for retrieving the lyrics from refreshing and recent tracks. I wouldn't trust the http connections to ever return even with a timeout unless I was really familiar with it, I'd have a way to basically abandon the threads and ignore callbacks after my own timeout, otherwise you could get in situation where it simply not refresh anymore, unless the app was force stopped.

**Comment by geecko86** [comment]
Alright, can you open an issue for this?

**Pull request merged**
