### PR TITLE
Added J-Lyric provider and jSoup for easier html parsing

### PR DESCRIPTION
**Pull request by beschoenen**
I've added jSoup for easier html parsing so that adding providers which do not provide an api can be added a lot easier.
I used jSoup to add J-Lyric. J-Lyric is one the biggest providers for Japanese songs.

### CODE REVIEW

**Comment by beschoenen** [comment]
A screenshot showing that it works


The provider can't be used for searching, at the moment.

**Comment by geecko86** [comment]
Hey there Kevin!

Using Jsoup is an excellent idea, especially since we'll need to add more lyrics websites in the future. And props to you for adding a Japanese website, I could never have done that. Awesome!

I'll merge, but first, could you amend your first commit and use a Maven dependency instead of a binary file? It's more convenient, especially for the folks over at F-Droid.

     compile 'org.jsoup:jsoup:1.8.+'

**Comment by beschoenen** [comment]
Is there something else i should implement into the J-Lyric provider?

**Comment by geecko86** [comment]
Alright! It's merged. I made a couple of changes:
1) I renamed the getLyrics method to fromURL. 250fb89
2) I made it possible for fromURL() to function without the metadata and made it possible to open j-lyric.net pages with the app. 6282781

GitHub won't mark it as merged though... Probably should've applied my changes in the master branch. Oh well.

Regarding the search, it seems like you can only search with tags on this website (although I don't speak japanese so I could be wrong), making it incompatible with the current search implementation where the user types their own query.

Thanks man! And if you have the time, there's some translations to be made in flemish (dutch) on the [Crowdin page](crowdin.com/project/quicklyric/invite).

**Comment by beschoenen** [comment]
I currently parse the search page and pick the first results, but you could make a list of all results and use them.
If you give me some pointers as to where i should call my methods, I'd be happy to look at it.

**Comment by geecko86** [comment]
You can see how they've been renamed in the commit I just listed as 1). :)

**Comment by geecko86** [comment]
I don't listen to Japanese music, but according to you, how much has it improved since you added j-lyric? Is there still room for improvement for Japanese lyrics?

**Comment by beschoenen** [comment]
I didn't really have time yet to further look at it. But i think it could use some improvement in speed because it has to load 2 full web pages. Also i want to add the ability so be able to search on the provider.

**Pull request closed without merging**
